services:
  db:
    image: postgres:16
    container_name: personal-finance-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_finance
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data # O nome do volume é pgdata e vai buscar os dados guardados do postgres
  redis:
    image: redis:7
    container_name: personal-finance-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redisdata_dev:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-finances-app-dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app # Isto é o bind mount, que é apontado a partir do caminho do docker-compose para o que foi gerado no Dockerfile ( o workdir app).
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm install && npm run start:dev"
volumes:
  # Os volumes que são named, têm de estar aqui definidos ao mesmo nivel dos services, e cada um com ":" à frente sem nada definido
  # Os bind mounts não precisam de estar especificados aqui
  pgdata_dev:
  redisdata_dev:
