services:
  db:
    image: postgres:16
    container_name: personal-finance-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_finance
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d personal_finance"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: personal-finance-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: personal-finances-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "3000" # só rede interna
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: personal-finance-nginx
    depends_on: [app]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    # reload automático a cada 12h (p/recolher certs renovados)
    command:
      [
        "/bin/sh",
        "-c",
        "nginx -g 'daemon off;' & while :; do sleep 12h; nginx -s reload; done",
      ]
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: personal-finance-certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    # tenta renovar de 12h em 12h (silencioso)
    command:
      [
        "/bin/sh",
        "-c",
        "while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h; done",
      ]
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  certbot-www:
  certbot-conf:
